CREATE TABLE survey
(
    SurveyId                  INT NOT NULL AUTO_INCREMENT,
    SurveyName                VARCHAR(100) NOT NULL,

    CreatedAt                 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt                 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    PRIMARY KEY (SurveyId)
) ENGINE=innodb AUTO_INCREMENT=1000;
